namePrefix: capoci-

namespace: capoci-system

labels:
- pairs:
    cluster.x-k8s.io/provider: "infrastructure-oci"

resources:
  - ../../config/rbac
  - ../../config/manager

patches:
- target:
    kind: Deployment
    name: controller-manager
    namespace: system
  path: manager_controller_patch.yaml
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: remove
      path: /spec/template/spec/serviceAccountName
- target:
    kind: Namespace
    name: system
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: system
