apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - "--leader-elect"
        - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=true}"
        - "--metrics-bind-address=127.0.0.1:8080"
        - "--logging-format=${LOG_FORMAT:=text}"
        - "--init-oci-clients-on-startup=${INIT_OCI_CLIENTS_ON_STARTUP:=true}"
        - "--enable-instance-metadata-service-lookup=${ENABLE_INSTANCE_METADATA_SERVICE_LOOKUP:=false}"
        - "--webhook-port=0"
